var request = require('request-promise');

var na = ['Class A:RAHUL KUMAR AGRAHARI',
'Varun Goel',
'CHINMAYA MARIAPPAN',
'Akash Verma',
'RAHUL KUMAR AGRAHARI',
'RAVI PATEL',
'Pratyaksha Kumar Srivastava',
'Amit Kumar Singh',
'PRABHAT KUMAR',
'SOUMYADEEP PAL',
'ARYAN BHARADWAJ',
'Manaswini Mishra',
'CARLIN SAVIO JUDE FERNANDES',
'PRATEEK DHAMA',
'SHIVASAILAM SENTHILVEL',
'URVI JOSHI',
'SAYAN MOHANTY',
'SHARATH SHIVA RAM R',
'SHARATH SHIVA RAM R',
'PANDU RANGAN NIKHIL',
'BENATTO B B',
'S DINESHA',
'Devashish Sharma',
'KONDAPUDI SANTHOSH KUMAR',
'DIPALI SINGH',
'Tanmay Toshniwal',
'Vipul Jain',
'Pulkit Sambhavi Singh',
'Shikhar Saxena',
'VAIBHAV KALANTRI',
'Gokul K',
'PARTH MISHRA',
'NIRNAY MAHAPATRA',
'BHASKAR JHA',
'Vinayak Bora',
'AVI MISHRA',
'SHUBHAM SHARMA',
'UJWAL PANKAJ JAIN',
'SATYAM',
'Nikhil yadav',
'Ayush Gupta',
'ROHAN SHARMA',
'amod ranjan tripathi',
'LINGAM HEMANG',
'ANKIT HANS',
'HARISH MISHRA',
'ALAVALA SATYA SAI CHARAN',
'DHRUVRAJ SINGH RATHORE',
'NAMAN BHASIN',
'KANDAGATLA MITHUN KUMAR',
'S Neel lohit',
'SUBHRADEEP NAG',
'SIDDHARTO SURCHOWDHURY',
'KANIGICHERLA BALAJI SUBRAHMANYAM',
'SHIVAM KUMAR',
'VIGNESH R',
'VIGNESH VISHNU CHANDRU  A',
'TUSHAR VERMA',
'Yashu Kedia',
'SMRUTHI  RAMESH',
'TAPISH SHARMA',
'Nachu varunkumar',
'Sathya Prakash G',
'ADITYA PRATAP SINGH',
'Prabhav Srivastava',
'J V RISHI',
'Komal Rastogi',
'RITISH CHAUDHARY',
'Divyansh singhal',
'ARPIT DAKHERA',
'GAURAV GARG',
'SUSHANTH S',
'TEJA PAILA',
'Rishabh Pagaria',
'Srijan Pathak',
'Swathy Gopal N',
'SHINJINEE MAITI',
'Shubhayu Chakrabarti',
'Dileswar Sai Dheeraj Yagitela',
'Rushil Rai',
'Siddhant Dogra',
'PRANJAL DATTA',
'NEETISH KUMAR SINGH',
'ANIKET KUNDU',
'C VARUN',
'PARTH DHAWAN',
'SWATHIK SAJEESH',
'Mudit Kumar Jain',
'SHUBHANKUR MECHU',
'Hardhik Sharma',
'AISHANI SINGH',
'Siddharth ladha',
'DHRUV SIKKA',
'PIYUSH DHAKAR',
'ISHWARIYA  A',
'Kevin Philip',
'Aishanya Shanvi',
'MAHINDRE SANJANA SUNIL',
'SMRUTHI  RAO',
'ASHUTOSH PRASHUN',
'VIVEK SINHA',
'SAUHARD SINGH',
'ANKIT MATHUR',
'ZUBER RAHMAN',
'CHEVULA LALITHESH REDDY',
'SPARSH SRIVASTAVA',
'J RAKESH',
'Kinnari S Shah',
'AKASH TIWARI',
'PRAVEEN KUMAR K',
'R ABDUL RAZIQ',
'GADAMSETTY CHARITHA RATHNA',
'DHIMAN SAIKIA',
'CHIPPA HRUTUJA VINAYAK',
'ARAVIND G',
'SHANTANU S',
'KRISHNIKA PANKAJ GULATI',
'NIDHISH NANDAN V',
'Devansh Gupta',
'SRIVIDYA  K.S.',
'Dhananjai Govind',
'KONCHA SIVA KARTHIK REDDY',
'PEDDITI VINISH REDDY',
'KAPIL AGARWAL',
'KUSHAGRA GUPTA',
'V GOKUL KRISHNAN',
'RAJ KUMAR',
'KUNWAR DANISH',
'KAVYAPRIYA R',
'SHUBHAM SINGH',
'THEJASWIN S',
'SUMITHRA  A',
'Rahul Nandkumar',
'SOUMITRA CHATTERJEE',
'GUTHI CHARAN REDDY',
'SATYANARAYAN JAGANATHAN',
'Raghav Mundra',
'S SRINIDHAN',
'Sankar Narayan Banerjee',
'Sai Barath R',
'DEEPKUMAR SUTARIA',
'ABHUDAY MISHRA',
'HARSH GUPTA',
'ULLASHVARAN SURESHVARAN',
'AVI GAUTAM',
'Katla pramod kumar',
'ARNAB KANU',
'Siddharth Singh',
'Venkatesh R',
'Divye Suri',
'Parteek porwal',
'MOHAMMAD KAMRAN',
'Ravinuthala Prasanth',
'Rachit Narayan',
'Ayush Shrivastava',
'H UTKAL RAO',
'K Shakthi prasad',
'AMIN HASAN MURTUZA',
'shambhavi dubey',
'ALLEN ABHISHEK R',
'Supriya  M',
'PAMIDI KUMAR CHOWDARY',
'AKASH SONI',
'Kshitij',
'SAJAL TYAGI',
'vibhesh sharma',
'CHERUKURI D NAGENDRA .',
'Ansuman Biswas',
'D Arun Singhvi',
'Krishnanand G',
'KINJAL K PARTH',
'Shubam Mehta',
'Anshuman Singh',
'Kartavya Jolly',
'SHIVAM KUMAR SINGH',
'ARPIT MANOCHA',
'Korrakuti Mounika Chowdary',
'SHREYANSH KHANDELWAL',
'SAINATH ARJUN M',
'Sampada Bareja',
'v bharath chandra',
'Angsal Chetri',
'ADHIPATYA SONBHADRA',
'LABALA MITHILESH',
'Hiba Bano',
'BRAHMANDAM SRINIKETH',
'S S V R PRUDHVI TEJA NIDADAVOLU',
'SMITH PATEL',
'NEERAJ BHATIA',
'Parisha Tandon',
'ARYAN BHATNAGAR',
'SUBHAM PARIDA',
'Vindhya prakash',
'Manish Panda',
'Shadab Raza',
'Partha De',
'T Soorya Kiran',
'MD FARDIN HOSSAIN',
'ADITYA DIXIT',
'HARSHAL GARG',
'Chirag Gomber',
'SOMIK CHOWDHURY',
'sarthak gupta',
'MOHAMMAD HAZIQ BABA',
'RESHESH KUMAR PATHAK',
'ROHIT RANJAN',
'Nikhilesh Ram',
'Shah Yatik Rashmin',
'UMESH KUMAR MISHRA',
'SHIVAM SINGHAL',
'ASHWIN SILLA',
'Abdul Rahim Ismail Rumaney',
'ABU TALHA',
'heet patel',
'Abhishek Jangid',
'RAMASAHAYAM SRIKAR REDDY',
'Ashish raj',
'Aman Sodani',
'Bikrant Sen',
'Arnab Deep',
'NAVEEN SINGH',
'JASRAJ SINGH RANDHAWA',
'PRAMIT KUMAR BHADURI',
'ABHISHEK KUMAR DEEPAK',
'DEBTANU DEY',
'Amit Kumar Singh',
'DIVYANSH JAIN',
'ANISHA MOHANTY',
'LAKSHMINARAYANAA R',
'SARTHAK ASTHANA',
'VAIBHAV SUWALKA',
'ANIMESH KUMAR SINGH',
'RATANSHI PURI',
'KOMMOJU VENKATA NAGA AASRITH',
'SIDHANT SUMAN',
'AKASH R',
'Pranat Siyal',
'SPARSH AGARWAL',
'AMAN KUMAR',
'Devansh Dwivedi',
'ANKIT SHAH',
'RAKSHIT PURI',
'Mritunjay Singh Bhadauria',
'AAYUSH MEHTA',
'BARATH KUMAR B',
'MEEHIR MALIK',
'KRISHNAVAMSI ATLURI',
'sajal jaiswal',
'ABHISEK MOHANTY',
'Manan Verma',
'KARTIK KUMAR SRIVASTAVA',
'Shylaish Velayutham',
'BANDI SUDHEER',
'SWAROOP NANDY',
'ARVINDER SINGH MUNDRA',
'G M JISNU',
'Shreya Raghuvansh',
'SAI PRASADH M',
'Abhishek Samanta',
'CH V S S TEJESH',
'AIKATVA JAIN',
'SETH SUKESH RAKESH',
'SMEET MEHTA',
'Dharini Grover',
'GANTI MAHAPATRA ANUSHA',
'Devansh Taneja',
'PARIKSHIT VERMA',
'Aman chawla',
'SHOURYA ANANT',
'Aayush Dua',
'SIDDHANT SAXENA',
'Shaik Ahaan Kareem',
'Maria Vasanth Ashale',
'Tanvi choudhary',
'Ankur Rana',
'AARUSHI SHARMA',
'SATYAM PRASHER',
'CHIRAG BENGANI',
'Nandhini S',
'AYUSHI MATHUR',
'Aayush Agarwal',
'SIMRAN VERMA',
'BHAVISHYA DHIMAN',
'PATEL SAMARTH RAHULDEO',
'Aryan Pandey',
'TALASILA BABY SAROJINI',
'SHAUN THOMAS THOMAS',
'ADARSH SHAILENDRA',
'Bodhisatta Das',
'ANIRBAN GHOSH',
'PARIDHI RAI',
'A YOGI ATHISH',
'PASALA RAKESH',
'ARNAV NAMDEO',
'MD DANISH REYAZ',
'VASUDHA GROVER',
'KAVIYA S',
'Vinamra Parashar',
'SHIBUSHREE ABHISHEK',
'Asutosh Agarwal',
'Dharani Vasan',
'AVI GOYAL',
'Shubham Nagpal',
'NIKHIL LADDHA',
'PALLE ARAVIND GOUD',
'SUBHAM SOURAV',
'PARIDHI TALWAR',
'MANTHA SRIHARSHA',
'Abhishek Sridhar',
'A R SURIYADEVALAN',
'SAURABH RAJ',
'Saurav kumar',
'SAMALA ROHIT',
'AAKRITI NAG',
'ARRYAN SINHA',
'SUBHANKAR PRAMANIK',
'S P SHIBU JEYANTH',
'BORRA VENKATA SURYA DHARINI SANTOSHI',
'ASHWARYA RATHORE',
'Tushar Thakur',
'Imran Ahmed Khan',
'GAWADE SHREYAS DILEEP',
'D PRAHARSHA SAI',
'SUKESH V S',
'Dhruv Awasthi',
'KOUSALYA M',
'MANAN CHAWRA',
'VIKRAM SINGH',
'Akash Verma',
'GANDHI SAMARTH MANISH',
'DEWANSH CHATTER',
'DINESH KUMAR R',
'BHASKAR DHRUV KUNCHA',
'ANKIT MISHRA',
'EESHAN DUTTA',
'MALLU CHANDRA SEKHAR REDDY',
'GAURAV SINGH',
'MUKUND KUMAR',
'ADITI KHATRI',
'MAHARNAB CHATTERJEE',
'ARUN ARCHAN RAUTARAY',
'Akash Raghav',
'Divij Gupta',
'Rahul Agarwal',
'MALINI S',
'CHAKRAVARTY USHNISH CHIRADEEP',
'SHREE SAAIRONIT GARIMELLA',
'SRAJAN JAIN',
'Vishad Thusu',
'NACHIKETA CHOUDHARY',
'PRANAV B KASHYAP',
'AKASH G',
'BADDAM KOTI REDDY',
'R RAJKUMAR',
'VAISHNAVI UPENDRAN',
'ROHIT SUMIT KUNDU',
'MADDULURI VAMSI',
'NANDINI KAPOOR',
'PUSPAK DAS',
'Kriti Gandotra',
'SREEMAN S',
'ROHIT R NAIR',
'M NIRANJAN SURAJ',
'SADIQ SHAIK',
'NAMAN CHITKARA',
'Shubhamdeep Jha',
'Ankit Niranjan',
'ROHAN GUPTA',
'PRATYAKSH BHALLA',
'Anubhav Anand',
'Siddhant Jha',
'Siddhant Jha',
'K SURYANARAYAN',
'SHUBHAM BHALALA',
'ShashankChandrasekar',
'vishwa hariharan iyer',
'DHULIKA MEHTA',
'Shubham Shukla',
'KAUSHIK PANAMPARAMPIL MAHESAN',
'ANUSHKA AGARWAL',
'ATANU WADHWA',
'TIRNATHI PAVAN NAIDU',
'REHAN SINGH',
'MIHIR SINGH',
'CVY JAYANTH',
'SOUMYONEEL DEY',
'ABHISHEK SATHYANARAYANAN',
'KARISHMA  SRINIVASAN',
'RITWIK GUPTA',
'SUBRAT KUMAR',
'ARNAV THAKUR',
'V KEN HIYTESH',
'A SRINIDHI',
'SAI KRISHNAN ANANTHA NARAYANAN',
'PARAJ SHAH H',
'RAGHU B',
'VISHRUT VERMA',
'SIBY  ISAC',
'Trinayan  Borah',
'Vaibhav Singh',
'ABHIJEET PADHI',
'KUSSAGRA PATHAK',
'KOLISETTY SATHVIKA',
'SNEHAL SAUMYA',
'ISHAAN DUTTA',
'SWAMINATHAN V',
'SHUBHANKAR TIWARI',
'PRIYAM GARG',
'Abhishiek Bhadauria',
'Waris Reyaz Wani',
'Sagar Kumar Karmakar',
'AMAN KUMAR',
'UTKARSH JAIN',
'YAMINI U',
'MRINMOY PAUL',
'TANDURU CHERISMA',
'Jojula Anish Chandra',
'SUJAY GOSWAMI',
'Prince Abhishek',
'Ishvendra Singh',
'RISVANTH S',
'Prashant Kumar Das',
'VIBHAV BHRIGUVANSHI',
'SIVATHEJESWARA REDDY  K',
'BHARAT SINGHI',
'NITISH HANS',
'YUKTA VAJPAYEE',
'Mishika Agrawal',
'Kartikey Nagpal',
'ARYAN KAPOOR',
'LALITH KISHORE S',
'SHUBHAM SHANTVEER PATIL',
'Nimish',
'Abhishek Pillai',
'BONDADA KUMAR KARTHIKEYA',
'ISHITA',
'Ishita Singh',
'SANTHOSH KUMAR R',
'Abhisekh Behera',
'Achintya Daga',
'SHOUHARDIK SAHA',
'YANGAIAHGARI VENKATA GOVARDHANA',
'KEVIN T JINU',
'PAVITRA GOLCHHA',
'KARIMELLA CHAKRAVARTHI VISWANATH',
'NARAYANAN P K',
'ADITYA CHANDRASHEKAR',
'Vatsal Saxena',
'ARYAN ANAND',
'AVADH CHAUHAN',
'NISHOK ILANGOVAN',
'Rashi Gambhir',
'NERUSU NAGA VEERA VENKATA SATYA SIVARAM',
'APARAJITA SAHOO',
'SHAIK MOHAMED TOUSIF',
'SRIHARI KARTHIK',
'AKSHAT SACHAN',
'SIDDHANT THAKUR',
'Dhruv Upadhyay',
'Shreyansh Gupta',
'Dhruv Kumar Singh',
'PITCHIKA TANMAYI',
'TULASI MANIKANTA',
'NANDITA MENON',
'Lipika Prasad',
'ROHIT M',
'MARAM.PITCHI REDDY',
'MITRAJSINH HARISHKUMAR KHER',
'RAMACHANDRAN A',
'DHRUV BAJAJ',
'SHANKHA SUBHRA BISWAS',
'Aditya jain',
'BHAVESH KRISHNA AGARWAL',
'Sriman S',
'KODUKULA GAUTAM TUSHAR',
'Nilay Baranwal',
'DEVDARSH V PANTH',
'ROSHAN KRISHNACHANDRA JHA',
'AYYULURI VENKATA SATYA SRIRAM REDDY .',
'THONTEPU DATTA NAGA SRI MANIKANTA',
'Anish Kumar Gupta',
'RAGHAV HARALALKA',
'ABHYAS MALL',
'Rohan Agrawal',
'SHOHAG DUTTA',
'YELLAMELLI SATYA SAI TEJA',
'Ayush parida',
'REETESH KUMAR',
'Andra Monish',
'Soham Saha',
'ARYAN KUMAR',
'S ADITYA',
'RAHUL RYAN SAVIO',
'PALAPARTY SRI SURYA JITENDRA',
'Abhinav tripathi',
'SAI ADARSH PETA',
'DEV AWASTHI',
'Ali Qazi',
'ABHIGHYAN BOMMERLA',
'ABHINAV RAWAT',
'Gaurav Neeraj Bhatia',
'ROHAN MITRA',
'AISWARYA S',
'Shushrut Kumar',
'Saumitra Joshi',
'ARPITA MULEVA',
'Saumya singh',
'Srijan Saha',
'ABHISHEK SINGH',
'PAARTHASSARATHY S',
'Sagnik Roy',
'BHARGAVI PANDIT',
'MUKESH KUMAR PANDIA',
'AYUSH KUMAR GUPTA',
'AADESH PARIJA',
'Nilaabh Keshav',
'PEDDASURA PURNACHANDRA REDDY',
'PASUPULETI ESWAR VAMSI KRISHNA',
'SHAIK MOHAMMED RAZZAQ',
'Harshil Patel',
'Yayati Chandel',
'NAVEEN KUMAR P',
'Anubhav Rajauria',
'NAMYA HEMAL SHAH',
'AADITYA PRATAP PANDEY',
'Shivansh Upadhyay',
'ANNANYA PANDEY',
'MADHAV',
'SPARSH RASTOGI',
'I SAVAN SIDDHARTH',
'tanya aggarwal',
'YASH BATRA',
'AISWARYA PRADEEP',
'ROHIL KULSHRESHTHA',
'Pragya Moondra',
'SHAURY PRATAP SINGH',
'muskan didwania',
'Aayush Upadhyay',
'Akshat Prakash Srivastava',
'DIVYASH SINGH',
'LOKESH B',
'VEDANSH VIJAYWARGIYA',
'HARSHITHA V',
'SHAH KARAN MANISHKUMAR',
'MOHAMMED RAKIB CHOUHAN',
'ANISHA JAIN',
'D TEJA SIMHA REDDY',
'SARTHAK SAXENA',
'SHRISTI SRIVASTAVA',
'ABHISHOM BHATTACHARYA',
'YAZID MARZUK K P',
'KADIYALA YASASVI PRASAD',
'KARTIK BANSAL',
'VENNA PAUL JASWANTH REDDY',
'Joel Jaimon',
'PAVITRA PARAMESWARAN TRICHUR',
'AYANAVA SAMANTA',
'SHOBIT PURI',
'HARSH RAJ',
'Harsh kumar burnwal',
'Souradeep Mondal',
'Anshumaan Mishra',
'Divyang',
'PRATEEK SHARMA',
'RAGHU RAJ MUNI',
'PRAGATI PANDEY',
'Priyanshu',
'Vaibhav kumar',
'S EVERLY PRECIA',
'Sivin Varughese',
'ANSHUL CHITRANSH',
'BHAVNEET SINGH',
'PALAKURTHI SREEKANTH',
'MATTE REVANTH HARI NARAYANA',
'Rohit Ramesh',
'ARYAMAAN PARIDA',
'Ajeesh Philip',
'Dhanisha Agrawal',
'Shrajel punit',
'SUMRIT GROVER',
'PARITOSH SAXENA',
'NIKHIL SAJI',
'A N V SREEVISHNU',
'SAHIL SARAF',
'AVINASH BHARGAV KOMPALLI',
'SEJAL KUMARI GUPTA',
'Sameer Ahad',
'Karan Sanal',
'Adhiraj Bhagawati',
'MRETUL MADAV.B',
'SAKSHAM ANAND',
'POUSHALI DEB PURKAYASTHA',
'HARDIK SRIVASTAVA',
'Tamojit Sarkar',
'MAYANK SINGH',
'SHANTANU BHARTI',
'MRUDULA SATHISH',
'RISHAB SUDISH',
'RAVURI MANOJ KUMAR .',
'ANKIT SHUKLA',
'SREYASH',
'RANVIR SINGH',
'SABBAH AHMAD NEYAZI',
'BASIVI REDDY VENU GOPAL REDDY',
'SHUBHAM KUMAR GUPTA',
'KAUSHIK M',
'GEETANSHU KHANDAGADE',
'GEETANSHU KHANDAGADE',
'RAJESHWARAN NARAYANAN',
'Sweth S V',
'AARAV SHAILESHBHAI KARIA',
'JAYAPRIYA  SIVASANKARAN',
'N PRASHANTH',
'KRISHNA PRABEESH KAKARLA',
'SHANKAR NARAYAN R',
'JOBIN A B',
'RAAJ LAKSHMAN R A',
'SAGNIK BISWAS',
'MRIDUL GARG',
'arpan sharma',
'Asutosh Agarwal',
'Abhijatya Meena',
'jadia naitik prakash',
'Dhruv Mutreja',
'KARTIK SAINI',
'TARUN SINHA',
'KOLAKALURI GIRES',
'Amaan Aijaz',
'NISHITHA VELAGALA',
'AKSHAT ASHISH CHOUDHURY',
'Sauvik Das',
'Moinak Roy',
'Abhinandan Chanchal',
'Aswin R',
'GAURAV KAUSHIK',
'Saurabh kumar',
'YASH RAJORIA',
'A KAVINCHANDAR',
'ABHISHEK CHAUDHARY',
'Akshaya vinod kumar',
'RISHU KUMAR',
'SURYANSH SHRIVASTAVA',
'S KARPAGAVISHALINI',
'PRANAV GUPTA',
'SHIVAM PANDEY',
'RAJESHIRKE VEDANT NITIN',
'MANSI B',
'Shubham Kumar',
'Hashim Qureshi C',
'ANOUSHKA SINGH',
'ADITI PATEL',
'Antariksh Ray',
'VISHAL P',
'RIDDHI AGARWAL',
'AYUSH GUPTA',
'SUMIT OJHA',
'ASHWIN V NAIR',
'MOHIT SAHNI',
'PRASANJEET KESHRI',
'SAMANTA TIYASHA TUSAR',
'Eshaan Arya',
'SHAURYA VISHNOI',
'SHAMBHAVI BAJPAI',
'NIKHIL UNNIKRISHNAN',
'SHUBHRA',
'SHAILENDRA SUDAKAR',
'Kalidas Jayanand',
'Shaurya Bhandari',
'Shivank Tripathi',
'PRAKHAR SHUKLA',
'ABBINENI ABHIRAM',
'yash pandey',
'HARSH SRIVASTAVA',
'ADITYA AGARWAL',
'RAJAGOPAL R M',
'J THARUN KUMAR',
'Shatoddruh Saha',
'REDDIPALLI SRI REVANTH',
'R RAJ NAVIN',
'PULLEPU HEMANTH DEVI PRASAD',
'VISHAL A RAWAL',
'ABHINAV TYAGI',
'ANSHUL TYAGI',
'AAYUSHI GOENKA',
'MOHAMMED AMAAN UR RAHMAN',
'Pranshul Dobriyal',
'AADITYA SAXENA',
'KUTIKUPPALA CHARAN',
'RAJAT DANG',
'CHAPPIDI PAVAN PREETHAM REDDY',
'MANOJ KUMAR S',
'MRINAL NANJAPPA',
'VISHNU VARDAN BABU PENTELA',
'VISHNU VARDAN BABU PENTELA',
'MOKSHAGUNDAM MANOJ SRIVATHSAVA',
'JAYANTH NARIYAM',
'SERENE RAJ',
'SHAIK FIRDOSE',
'OBILLANENI ROHITH KRISHNA SAI',
'HARSHAVARTHANAN L',
'ASWIN KRISHNA',
'SAHIL RAO',
'P HIRISHIKESH',
'SAYYED MANSOOR AHMED',
'VUPPALA VAMSI',
'PANATI CHANDU',
'Devi R',
'SUSMITHA S',
'Sarojini S',
'ARPITA SARKER',
'HARSH JALAN',
'ANISETTI POORNA CHANDRA SAI',
'RIA TYAGI',
'MARAM VENKATA RAGHU RAMIREDDY',
'Tushar Pandey',
'MATETI KEERTHAN RAJ',
'YASH SAMEER SUNKLE',
'ARYAN BHARDWAJ',
'Gitto Q Wesley',
'Shivang Abrol',
'AYUSH RAJ',
'K EASHA NAIR',
'Manav Gupta',
'Rishabh Santosh Shukla',
'Saurabh Gupta',
'ARYAN RAI',
]

var yr = ["191100","181100","201100"];// RA year

var branch  = ['CSE', 'computer Science','Biotech', 'IT' , 'Cse' , 'Mechanical' , 'BIO', 'Aero','Electrical', 'CS bigData']

var q = function makeid(length) {
    var result           = [];
    var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for ( var i = 0; i < length; i++ ) {
      result.push(characters.charAt(Math.floor(Math.random() * 
 charactersLength)));
   }
   return result.join('');

   ddr = result
   return;

}


function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
}


var chars = 'abcdefghijklmnopqrstuvwxyz';



//var ques = ['WHen is the event','When is the event?','Timings of this', 'None','N/a',' ','Freshers can attend?', 'sksdjsandf safdois','sadfjasifaoifowauehouwfinasdiuf','sadpfisadfohsoufd','sdfhdif','apdsifoaioafoesyfneyf0aef','asufhasufdhiaufduafuiwgiubag','sduhfhusadfusfadf','sdifsafds','sdfsdfsdfsfasfsaf']


var ques = ['WHen is the sadfsdfsdfdsfsdfeventsdfsdf','When asdfsadfsdfis the event?','Timinasdsjdfifgs of this', 'Nsdfsdfsfone','N/a',' ','Freshers can attend?', 'sksdjsandf safdois','sad;;fjasifaoifowauehouwfinasdiuf','sadpfisadfohsoufd','sdfhdif','apdsifoaioafoesyfneyf0aef','asufhasufdhiaufduafuiwgiubag','sduhfhusadfusfadf','sdifkk;lksafds','sdfsdfsdfsfasfsaf','sdfhsdh duhusafdh iu sidf safd i','ouyiuiyiyiyioyi','iuiggugfufiyt','iyguyguygugug','vvjhhhvvhbbjhbjbhjh']


//var ques = ['asdasd','asdasd']
var i ;
for(i=0;i<30;i++)  {

    a()
   console.log("eeee")
}



async function a (){


var options = {
  'method': 'POST',
  'url': 'https://docs.google.com/forms/u/0/d/e/1FAIpQLSfDjwf-gTvNJsi1b8GmBK7nQPVx1aSd-TS8cHKtRMMN-FopgA/formResponse',
  'headers': {
    'authority': 'docs.google.com',
    'cache-control': 'max-age=0',
    'sec-ch-ua': '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'upgrade-insecure-requests': '1',
    'origin': 'https://docs.google.com',
    'content-type': 'application/x-www-form-urlencoded',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'x-client-data': 'CIW2yQEIo7bJAQjBtskBCKmdygEIlqzKAQj4x8oBCJ/lygEIsZrLAQjknMsBCKmdywEI6J3LARjhmssB',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-user': '?1',
    'sec-fetch-dest': 'document',
    'referer': 'https://docs.google.com/forms/d/e/1FAIpQLSfDjwf-gTvNJsi1b8GmBK7nQPVx1aSd-TS8cHKtRMMN-FopgA/formResponse',
    'accept-language': 'en-US,en;q=0.9',
    'cookie': 'S=spreadsheet_forms=Wfyr4MFRKWsqoDIGG6Xx9RLEd_c8KKHGJlYikQjxTfQ; ANID=AHWqTUmSxtIwYXgvCbrrTwwmF9UwpNBHlDRwc7_HYJpFdxdeti6RJiRQaAG5tQr9; SID=8gcrBUVkq5ilucjOwPoXu7KWTD955b5NgIheu0mMpBKVPWp3DD9mTSto9W976wkuYOKxPw.; __Secure-3PSID=8gcrBUVkq5ilucjOwPoXu7KWTD955b5NgIheu0mMpBKVPWp3gOdDQPmNT_gbYj6p1H6Lag.; HSID=Ao12a89DM079hjKCX; SSID=A6RzAfxs6aP1xSVc0; APISID=ZAheAdiCNsuxhSNI/Alao6bWiCPqGcIFCp; SAPISID=cJBFE5w8gRIgSa7D/ARNCBdTGZ0gT1ER_-; __Secure-3PAPISID=cJBFE5w8gRIgSa7D/ARNCBdTGZ0gT1ER_-; NID=213=oB2IlMqnAFUv4G9uhFdDLONBDK5Q0Gngsqpn-cHi0grV-mFX2t5vwmNog54Aj9saTUR-cRvgHxHcwrgxTFcA3H19uZPXMa3SbxsgfADf4UiR4ghTkiI8tewukQShoJQ2_vwFvOKQmazJs6aDa7MLRKDQxDTEzvs7_9lsynWtOjSPvNC_Vn13h22hBCZp_pbXkQ_GKA0KAe_UZD7KoeKT8TvBRKqwoluNp0KYeMaDFPmPTw; 1P_JAR=2021-04-12-17; SIDCC=AJi4QfHY-AKjLAxsIzkI0naZoEsSn325ERO4jxeYkgLEYRzRLNcCfu9iU56jfztu2MTD2XpbS0XP; __Secure-3PSIDCC=AJi4QfG0NLj572EELEk6z2ZD2e4U44GnG-gfITbH8-iOdg18Yl0_8xaE7ofMmSGu0Vi39xzL2Pw; SIDCC=AJi4QfHLJm_yv5KgSgdgbzEkveUvzGrViLABbN3-DtR79FkORPlrr-piA_VJcAymbKIPh7dvSFr5; __Secure-3PSIDCC=AJi4QfEXE-ymM7cL8wmJ5I16Q55wpuGQyfeRacQ2lg3QyGyRT519metwaX9AogPbGE8JE_MjnfM'
  },
  form: {
    'entry.912183522': `RA${yr[Math.floor(Math.random() * yr.length)]}`,
    'entry.1792826308': `${Math.random().toString(36).substring(2,4)}${getRandomInt(1000,9999)}@srmist.edu.in`,
    'entry.255697082': `${branch[Math.floor(Math.random() * branch.length)]}`,
    'entry.393793487': 'I',
    'entry.393793487_sentinel': '',
    'fvv': '1',
    'draftResponse': `[[[null,1687432107,["${na[Math.floor(Math.random() * na.length)]}"]\r\n,0]\r\n,[null,2146005884,["${chars[Math.floor(Math.random()*26)]+ Math.random().toString(36).substring(2,11)}@gmail.com"]\r\n,0]\r\n,[null,234758700,["865${getRandomInt(1000000,9999999)}"]\r\n,0]\r\n,[null,52269382,["865${getRandomInt(1000000,9999999)}"]\r\n,0]\r\n,[null,570154455,["${ques[Math.floor(Math.random() * ques.length)]}"]\r\n,0]\r\n,[null,1407285364,["Student"]\r\n,0]\r\n,[null,822603084,["SRMIST"]\r\n,0]\r\n]\r\n,null,"-4454911317335846070"]\r\n`,
    'pageHistory': '0,1',
    'fbzx': '-4454911317335846070'
  }
};




await request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.statusCode);
  
});

    console.log('ho gaya')
}